import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/navigation/Navigation";
import { ClerkProvider, RedirectToUserProfile, SignIn } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs";
import type { User } from "@clerk/nextjs/api";
import { serverClient } from "./_trpc/serverClient";
import Provider from "./_trpc/Provider";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navigation />
          <div className="flex w-full px-2">
            <div className="w-full"><Provider>{children}</Provider></div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
